version: '3'

services:
  database:
    container_name: database
    image: 'mysql/mysql-server:8.0'
    environment:
      MYSQL_ROOT_PASSWORD: 99$E^xpq!x3k6RHiXdo4sTKVs
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: car_rental
      MYSQL_USER: car_user
      MYSQL_PASSWORD: cEc_5!EK9XdmWK3IRamLM^l2E
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - car_rental
  php:
    container_name: php
    build:
      dockerfile: ./docker/php.dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony_docker
    depends_on:
      - database
    networks:
      - car_rental
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/symfony_docker
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - car_rental
networks:
  car_rental:
    driver: bridge